var frds ={
    'friend':[
        {
            'name':'我不是夏东海',
            'level':'7',
            'want':'2019年新春交响音乐会',
            'gone':'看电影《海王》',
            'medal':'4',
            'src':'../imgs/friend/friend1.jpg',
            'sex':'male'
        },
        {
            'name':'我不是刘梅',
            'level':'4',
            'want':'话剧《罗密欧与朱丽叶》',
            'gone':'去了Xmas音乐节',
            'medal':'2',
            'src':'../imgs/friend/friend2.jpg',
            'sex':'female'
        },
        {
            'name':'被安排的明明白白',
            'level':'2',
            'want':'木偶剧《最后一头战象》',
            'gone':'看话剧《恋爱的犀牛》',
            'medal':'3',
            'src':'../imgs/friend/friend3.jpg',
            'sex':'female'
        },
        {
            'name':'我的妈鸭',
            'level':'6',
            'want':'看奥黛丽·赫本展',
            'gone':'看bigbang展览',
            'medal':'5',
            'src':'../imgs/friend/friend4.jpg',
            'sex':'female'
        },
        {
            'name':'哦我是你的小东',
            'level':'8',
            'want':'贰佰没有五演唱会',
            'gone':'看电影《惊奇队长》',
            'medal':'5',
            'src':'../imgs/friend/friend5.jpg',
            'sex':'male'
        },
        {
            'name':'嘿我不是你的小派',
            'level':'10',
            'want':'林宥嘉IDOL偶像演唱会',
            'gone':'看电影《惊奇队长》',
            'medal':'6',
            'src':'../imgs/friend/friend6.jpg',
            'sex':'male'
        },
        {
            'name':'我对象不是你对象',
            'level':'5',
            'want':'鹿先森乐队演唱会',
            'gone':'看话剧《哥本哈根》',
            'medal':'4',
            'src':'../imgs/friend/friend7.jpg',
            'sex':'female'
        },
        {
            'name':'迷恋坤坤的悦',
            'level':'1',
            'want':'看话剧《谈判专家》',
            'gone':'国家大剧院迎钟声音乐会',
            'medal':'0',
            'src':'../imgs/friend/friend8.jpg',
            'sex':'female'
        }
    ],
};